### ISSUE TITLE
any public bot on your server works?

### ISSUE THREAD

**Issue by Kwaskoff** [Codaone/BitShares-Telegram-notifier#1]

**Comment by juhanihaapala** [comment]
Hi @Kwaskoff, it is really easy to create your own bot https://core.telegram.org/bots#3-how-do-i-create-a-bot
There is a similar public bot in telegram with name "BitShares Assistant" you can try that.

**Comment by Kwaskoff** [comment]
I use @bitshares_assistant_bot and @bitshares_notifier_bot already and need one more bot =)
